settings:
  message_prefix: '&8[&bAdminEssentials&8]&a'
messages:
  player_frozen: '%message_prefix% &cYou have been frozen by an administrator'
  player_unfrozen: '%message_prefix% &cYou have been unfrozen'
  admin_freeze: '%message_prefix% &aYou have frozen &c%player%'
  admin_unfreeze: '%message_prefix% &aYou have allowed &c%player% &ato move again'
  chat_cleared: '%message_prefix% &aChat has been cleared by &c%player%'
  chat_currently_muted: '%message_prefix% &cChat is currently muted.'
  chat_mute_enabled: '%message_prefix% &aChat has been muted by &e%player%'
  chat_mute_disabled: '%message_prefix% &aChat has been unrestricted by &e%player%'
  admin_mode_enabled: '%message_prefix% &eYou have been put into &d&lADMIN MODE'
  admin_mode_disabled: '%message_prefix% &eYou have been removed from &d&lADMIN MODE'
  admin_mode_enable_others: '%message_prefix% &eYou have put %player% into &d&lADMIN MODE'
  admin_mode_disable_others: '%message_prefix% &eYou have removed %player% from &d&lADMIN MODE'