settings:
  server_name: 'MyServer'
  message_prefix: '&8[&b%server_name%&8]&a'
messages:
  player_frozen: '%message_prefix% &cYou have been frozen by an administrator'
  player_unfrozen: '%message_prefix% &cYou have been unfrozen'
  admin_freeze: '%message_prefix% &aYou have frozen &c%player%'
  admin_unfreeze: '%message_prefix% &aYou have allowed &c%player% &ato move again'
  chat_cleared: '%message_prefix% &aChat has been cleared by &c%player%'
  chat_cleared: '%message_prefix% &cChat is currently muted.'